### ISSUE TITLE
from readme_moodle.txt: grunt js fails (no package.json or gruntfile.js) 

### ISSUE THREAD

**Issue by js0000** [jleyva/moodle-block_configurablereports#116]
trying to follow the steps in the readme_moodle.txt file in the root directory and i've come across an error. when i run grunt js (i'm assuming to minify the js) i get this:
`% grunt js 
grunt-cli: The grunt command line interface (v1.3.2)

Fatal error: Unable to find local grunt.

If you're seeing this message, grunt hasn't been installed locally to
your project. For more information about installing and configuring grunt,
please see the Getting Started guide:

https://gruntjs.com/getting-started
`
and there's no package.js nor Gruntfile.js within the repository ...

so i'm skipping this step for now.

this might be a bug, or is there an expectation that anyone reading that far will be able to generate these files themselves ... ?

**Comment by sarjona** [comment]
Hi @js0000! 

Thanks for reporting it! Grunt should be configured following the indications on https://docs.moodle.org/dev/Grunt

Once installed, it should be executed from the moodle root folder and will only generate new files if there are changes at any of the files defined in https://github.com/jleyva/moodle-block_configurablereports/blob/MOODLE_36_STABLE/readme_moodle.txt

I'm going to close this issue because it's working as expected.

Cheers!
