### ISSUE TITLE
Getting "array" output when using template

### ISSUE THREAD

**Issue by reboltof** [jleyva/moodle-block_configurablereports#118]
Using Moodle 3.6.3, mySQL 5.7, PHP 7.1 and plugin version available on 01/05/19

This is THE ultimate plugin for generating reports in Moodle ! But when using a template for beautyfulising the reports, I always get a page with "ArrayArray" (see picture) as answer in the report view page.

I did use the latest official version and the version you mentioned in this thread. Same results...

Please help, this template function is very important to me...

Thank you so much for the good work !

Christophe

![Screenshot 2019-05-05 at 17 40 10](https://user-images.githubusercontent.com/7195940/57303300-50f7a100-70dd-11e9-83ee-b96d93cd5184.png)

**Comment by reboltof** [comment]
Hello,

Any chance getting an answer on this please ?

TIA,

Christophe

**Comment by ertborTek** [comment]
I've run into the same issue and figured out that during the template replacement process, when "Available marks" are substituted with actual report data, string replacement is attempted on an array rather than a template string.  Specifically, in the `print_template()` function (in report.class.php) when the substitutions are made (around line 670), `$recordtext` is set to `$recordtpl`, which is an Array.  So, rather than seeing what you expect, you see the data type (Array) printed with no substitution occurring.  You can remedy this by changing `$recordtext = $recordtpl;` to `$recordtext = $recordtpl['text'];` since the text attribute is more likely the subject for replacement.  Maybe somewhere along the line `$config->record`, from which `$recordtpl` gets its value, was restructured.  Maybe someone can look into this and put together a proper pull request, checking that the type is what's expected and accounting for how this data element might have been structured in the past.

**Comment by reboltof** [comment]
Thank you for your answer. I'm more a python man, but I can find my way into PHP too... 
I placed the suggested mod into `blocks>configurable_reports>report.class.php ` in the loop:
`foreach ($this->finalreport->table->data as $r) {
                $recordtext = $recordtpl['text'];
                foreach ($this->finalreport->table->head as $key => $c) {
                    $recordtext = str_ireplace("[[$c]]", $r[$key], $recordtext);
                }
                echo format_text($recordtext, FORMAT_HTML);
            }`

And it worked !

Thanks for this hack ! Devs: any update coming pleeeeease ?

**Comment by reboltof** [comment]
UPDATE: using above patch, the body of the report is correctly rendered, but neither the header nor the footer. 
You'll need to apply the same correction to the following lines:
at about line 647: `echo format_text($pagecontents['header'], FORMAT_HTML);` => `echo format_text($pagecontents['header']['text'], FORMAT_HTML);`
at about line 670: `echo format_text($pagecontents['footer'], FORMAT_HTML);` => `echo format_text($pagecontents['footer']['text'], FORMAT_HTML);`

Now the reports can use templates !

**Comment by sarjona** [comment]
My apologies for the inconvenience. I added a commit some months ago to fix that issue (d572df17fbeb0639a897ad5027a5a2f5876e6390) but then I couldn't find time to release a new version.
I'm planning to release a new one soon which will include it :-) 

Thanks a lot for your help and your comprehension!

**Comment by KenFarr** [comment]
Many thanks for all the work on this brilliant plugin. We had the array issue described here on two sites. So we upgraded to the latest version of the plugin 3.7.0 2019060300 
This fixed the issue for the header and footer, but the main body of the report is still giving "array" repeated for each record, regardless of what is put in the Record Template.  I cannot see ertborTek's fix in the latest issue (but I am no php expert). Am I missing something?

**Comment by mcdoogs** [comment]
@KenFarr No, you're right - the fix was applied to the header and footer, but not to the records that get looped through for the body.
I'm new to Moodle, but it looks like something about the moodleform class (or maybe the html editor?) was changed - when the template form is submitted, an extra 'Format' variable is saved to the config along with the actual template data, resulting in the array. In order to be backwards-compatible with template data saved pre-change, you should check to see if the record is an array or not, as in d572df17fbeb0639a897ad5027a5a2f5876e6390.
So I replaced line 670 (`$recordtext = $recordtpl;`) with:
`if (is_array($recordtpl)) {
                    $recordtext = $recordtpl['text'];
                } else {
                    $recordtext = $recordtpl;
                }`
I submitted pull request #132 that should fix this issue - thanks!
