### ISSUE TITLE
MSSQL ROW_NUMBER() in a sql query crashes Configurable Reports

### ISSUE THREAD

**Issue by luisdev** [jleyva/moodle-block_configurablereports#120]
Moodle version: $release  = '3.5.2+ (Build: 20181027)';
Configurable Reports version: $plugin->release = '3.6.0';
OS: Windows Server 2012 R2
PHP v7.2.9 NTS Win32-VC15-x64
Database: Microsoft SQL Server 2016 (SP1) - 13.0.4001.0 (X64) 
Database driver: $CFG->dbtype = 'sqlsrv';
PHP SQLSRV extension version: 5.3.0+11108 

When I run the following query in a SQL Report 

```
SELECT COUNT(*) AS 'Users who have logged in today' FROM (
	SELECT
		ROW_NUMBER() OVER(ORDER BY lastaccess DESC) AS Row
	FROM mdl_user
	WHERE lastaccess > DATEDIFF(s, '1970-01-01 02:00:00', (SELECT Convert(DateTime, DATEDIFF(DAY, 0, GETDATE()))))
) AS Logins
```

Configurable Reports crashes with this error:

**[17-May-2019 11:08:50 Africa/Johannesburg] Default exception handler: Error reading from database Debug: SQLState: 42000<br>
Error Code: 102<br>
Message: [Microsoft][ODBC Driver 11 for SQL Server][SQL Server]Incorrect syntax near 'OFFSET'.<br>
SQLState: 42000<br>
Error Code: 153<br>
Message: [Microsoft][ODBC Driver 11 for SQL Server][SQL Server]Invalid usage of the option NEXT in the FETCH statement.<br>

SELECT COUNT(*) AS 'Users who have logged in today' FROM (
    SELECT
        ROW_NUMBER() OVER(ORDER BY lastaccess DESC) AS Row
    FROM mdl_user
    WHERE lastaccess > DATEDIFF(s, '1970-01-01 02:00:00', (SELECT Convert(DateTime, DATEDIFF(DAY, 0, GETDATE()))))
) AS Logins
 OFFSET 0 ROWS  FETCH NEXT 20000 ROWS ONLY
[array (
)]
Error code: dmlreadexception
* line 486 of \lib\dml\moodle_database.php: dml_read_exception thrown
* line 324 of \lib\dml\sqlsrv_native_moodle_database.php: call to moodle_database->query_end()
* line 431 of \lib\dml\sqlsrv_native_moodle_database.php: call to sqlsrv_native_moodle_database->query_end()
* line 897 of \lib\dml\sqlsrv_native_moodle_database.php: call to sqlsrv_native_moodle_database->do_query()
* line 77 of \blocks\configurable_reports\reports\sql\report.class.php: call to sqlsrv_native_moodle_database->get_recordset_sql()
* line 122 of \blocks\configurable_reports\reports\sql\report.class.php: call to report_sql->execute_query()
* line 71 of \blocks\configurable_reports\viewreport.php: call to report_sql->create_report()**

I posted more details here:
https://moodle.org/mod/forum/discuss.php?d=386483
https://tracker.moodle.org/browse/CONTRIB-7725

I don't have access to a MySQL or Postgres database so I can't test it on those platforms.

**Comment by scara** [comment]
Hi @luisdev,
CR always limits the result set at least to `BLOCK_CONFIGURABLE_REPORTS_MAX_RECORDS` records so that's the reason why you'll find the extra line `OFFSET 0 ROWS FETCH NEXT 20000 ROWS ONLY` i.e. the way to have a fixed page size in your modern SQL server - wondering if you have changed the block config `reportlimit` into `20000`  (_Administration > Plugins > Blocks > Configurable Reports > Report row limit_).
In other words it looks like CR supports only queries whose output is an actual result set made of 1 or more rows and not just a single row, here a number.

IMHO this could be an issue in the Moodle core code: `ORDER BY` is a key for the core code and `OFFSET` and `FETCH` clauses are the options of the `ORDER BY` clause but the core code already found an `ORDER BY` in your query, totally unrelated w/ the main query and that is the reason why a broken query will be executed by the core code.
You could try to add ` ORDER BY 1` at the end of your query which is not required but it should work in CR via Moodle - not tested:
```
SELECT COUNT(*) AS 'Users who have logged in today' FROM (
	SELECT
		ROW_NUMBER() OVER(ORDER BY lastaccess DESC) AS Row
	FROM mdl_user
	WHERE lastaccess > DATEDIFF(s, '1970-01-01 02:00:00', (SELECT Convert(DateTime, DATEDIFF(DAY, 0, GETDATE()))))
) AS Logins ORDER BY 1
```
A nice improvement in CR should be the possibility to add a special marker in a query to disable the automatic result row limit applied to all reports.

HTH,
Matteo

**Comment by luisdev** [comment]
Thanks Matteo.

I added "ORDER BY 1" to the sql in my report and Configurable Reports is now displaying the report successfully without the crash, so the ORDER BY seems to "fix" it.

And yes the **reportlimit** has been changed from the default 5 000 to 20 000 on my Moodle  (via the _Administration > Plugins > Blocks > Configurable Reports > Report row limit_ setting).

**Comment by sarjona** [comment]
Matteo, thanks a lot for helping Luis to find how to fix the issue.
In order to clean the tracker, I'm going to close it :-)
