### ISSUE TITLE
"Not allowed Words" when a string value contains a reserved word

### ISSUE THREAD

**Issue by Novocastrian** [jleyva/moodle-block_configurablereports#127]
Hi there! 

I have this line in a query that runs without errors in phpMyAdmin on my MariaDB 10.3.16 Moodle 3.7 database, but the Configurable Reports plugin errors out with the "Not Allowed Words" error.

```sql
select concat('<a target="_blank" href="%%wwwroot%%/course/modedit.php?update="',cm.instance,'">',l.name) as "Label",
...
```
phpMyAdmin MariaDB 10.3.16 (changing the prefix to the actual prefix in the database):
![image](https://user-images.githubusercontent.com/4601813/62912121-1da66b80-bdca-11e9-9c67-92e7fec59337.png)

Configurable Reports plugin 3.7.0 Moodle 3.7:
![image](https://user-images.githubusercontent.com/4601813/62912011-c86a5a00-bdc9-11e9-92b3-f5458db06c98.png)

Changing 'update' in the string (the URL required to open the label's edit page) to another word doesn't encounter this error. However, Moodle needs this in the URL to be a valid URL to the label's edit page. 

![image](https://user-images.githubusercontent.com/4601813/62911971-a7a20480-bdc9-11e9-8584-dea1993a30b5.png)

To my understanding, 'update' in my query is captured fine to not get caught being a [reserved word in MariaDB](https://mariadb.com/kb/en/library/reserved-words/), as it is encapsulated in double and single quotation marks, so I suspect this error has something to do with Configurable Reports. How can I resolve this?

**Comment by luisdev** [comment]
The problem is that the "update" in your hardcoded url is a reserved word as defined in **function validation_low_security()** and **function validation_high_security()** in \blocks\configurable_reports\components\customsql\form.php

Configurable Reports is a READ ONLY reporting tool. It doesn't allow you to run any commands that add, update or delete data.

So, to fix your problem and since you are using the CONCAT() function to create the SELECT query, you could break the "UPDATE" word up into two words and concatenate them together again in your CONCAT() code, like this:

`SELECT CONCAT(
    '<a target="_blank" href="%%wwwroot%%/course/modedit.php?upd', 
    'ate="', 
    cm.instance, 
    '">', 
    l.name
) AS 'Label'
FROM prefix_label AS l 
INNER JOIN prefix_course_modules AS cm ON l.id = cm.instance
WHERE  (cm.module = 12)`

That way Configurable Reports doesn't think that you're trying to include the UPDATE word in your SQL query, which it doesn't allow. Very hacky, but if it works, you can use it as a temporary fix until there's a propper patch for this.

Also, it's probably better to use propper JOIN syntax to join your tables instead of just the 
`and cm.instance = l.id`

**Comment by Novocastrian** [comment]
> The problem is that the "update" in your hardcoded url is a reserved word as defined in **function validation_low_security()** and **function validation_high_security()** in \blocks\configurable_reports\components\customsql\form.php
> 
> Configurable Reports is a READ ONLY reporting tool. It doesn't allow you to run any commands that add, update or delete data.
> 
> So, to fix your problem and since you are using the CONCAT() function to create the SELECT query, you could break the "UPDATE" word up into two words and concatenate them together again in your CONCAT() code

Ah! Yeah, it's hacky, but it works! Thanks for the suggestion 😄 

> Also, it's probably better to use propper JOIN syntax to join your tables instead of just the
> `and cm.instance = l.id`

This is also true. I quickly spun up this query for this ticket, as the query I'm actually working on is much more complex, with this code as a subset of it. 

Closing, but might be worth investigating where these reserved words are used in moodle URLs to allow users to generate the URLs like this.
