### ISSUE TITLE
Line graph

### ISSUE THREAD

**Issue by martinvivek** [jleyva/moodle-block_configurablereports#22]
If we limit the value less than 1000 only i can able to see the line chart, else image is not loading. 

Using Moodle 2.5
MSSQL 2005.
PHP 5.3.3

**Comment by sarjona** [comment]
Thanks for reporting this Martin.

Some improvements have been included to increase the time and memory limits when exporting: #71.
Besides, pChart library has been upgraded #101 , so maybe this issue has been fixed.

In order to clean the tracker, I'm going to close this issue. However, if you feel some work is still needed, add a comment here or open a new one (as you prefer), adding as much information as you can, like replication instructions.
