### ISSUE TITLE
Notices and warnings when adding user report

### ISSUE THREAD

**Issue by vaughany** [jleyva/moodle-block_configurablereports#47]
Hi Juan. I've just cloned your repo and installed the cr_23_stable branch into our development Moodle 2.9. I added the block to a course and added the Users report 'users course time dedication.xml' and received the following notices and warning:

```
Notice: Undefined index: customsql in blocks/configurable_reports/locallib.php on line 536
Notice: Trying to get property of non-object in blocks/configurable_reports/locallib.php on line 536
Warning: Creating default object from empty value in blocks/configurable_reports/locallib.php on line 536
```

Additionally, when cloning your repo it has the name `configurablereports` but when installing, Moodle complains that the folder name should be `configurable_reports`.

**Comment by sarjona** [comment]
Hi Paul!

Thanks for reporting this! It has been fixed in the following commit 94c6e5fa7ac9908ec98c635fe32951a9fc085b1c and it will be included in the next version :-) 

Regar to the folder name, thanks for you comment. I'ts explained in the installation instructions: https://docs.moodle.org/36/en/Configurable_reports#Installation
