### ISSUE TITLE
Moodle branch 2.2 error message

### ISSUE THREAD

**Issue by cklimash** [jleyva/moodle-block_configurablereports#7]
I recently installed your block on our 2.2 test instance of moodle and receive the following error message:
Field "courseid" does not exist in table "block_configurable_reports_report"

In looking at the install.xml, it doesn't appear that courseid is being added to the table.

**Comment by davosmith** [comment]
I was just about to report the same issue, but then I spotted this: https://github.com/jleyva/moodle-block_configurablereports/pull/3 which suggests that the 'MOODLE_22_STABLE' code is not 'stable' at all, but a broken, not currently being developed, 'development' branch.

There is not a clean upgrade path from the 2.1 => 2.2 version at the moment and, even if installed afresh, the 2.2 version uses a 'contextid' field instead of a 'courseid' field, except that several places in the code still refer to the 'courseid' field.

**Comment by nadavkav** [comment]
Davo Smith,
Here is a link to a working version of this plugin on a Moodle 2.3 stable system
https://github.com/nadavkav/moodle-block_configurablereports/tree/WIP-M23

**Comment by jleyva** [comment]
Sorry for my late response, the version in the plugins database for Moodle 2.3 works fine (https://moodle.org/plugins/pluginversion.php?id=1025),

 I only work in the MOODLE_21_STABLE branch, I should rename this branch to something like MOODLE_STABLE because I only keep one branch for all versions but I notice that some people is upgrading the module using git and this branch

Regarding the 2.2 branch, I'm going to rename it to UNSTABLE_NOT_WORKING

**Comment by davosmith** [comment]
Thanks :-)
