### ISSUE TITLE
3.2-compatible version

### ISSUE THREAD

**Issue by colin-umn** [jleyva/moodle-block_configurablereports#79]
Any guess as to when a 3.2-compatible version will be available?  Has anybody reported whether the latest version simply works as-is with 3.2?

**Comment by sarjona** [comment]
Hi @colin-umn!
Thanks for reporting this. I'm working on it and I hope to release a new version soon, with support to the most recent Moodle versions.
In order to clean the tracker, I'm closing this issue (you can find the new changes on the branch https://github.com/jleyva/moodle-block_configurablereports/tree/MOODLE_36_STABLE).
