### ISSUE TITLE
PHP7 issues

### ISSUE THREAD

**Issue by 2shediac** [jleyva/moodle-block_configurablereports#94]
When looking to use this plugin with PHP7, there are a couple of issues:
1. Function split() is deprecated since PHP 5.3 and removed since PHP 7.0; Use preg_split instead. This occurs in lib/pChart/pChart.class (and other places);
2. In js/datatables/extras/Scroller/media/data/server_processing.php, Extension 'mysql_' is deprecated since PHP 5.5 and removed since PHP 7.0; Use mysqli instead;

Let ,me know if you need more information

**Comment by sarjona** [comment]
Hi Derek!

Thanks for reporting this. 

1. The pChart library has been updated to the latest version compatible with PHP7. However, it is still not working, as you can see here: #101 
2. The datatables library has been updated and this file has been removed from the CR plugin: 8d7499bff8f4fa4b39418e10c08b016521448633

In order to clean the tracker, I'm going to close this issue. Please, feel free to add any comment in the related issues if you feel that some more work is needed :-)
