### ISSUE TITLE
pix_url should be replaced with pix_icon or image_url

### ISSUE THREAD

**Issue by michael-milette** [jleyva/moodle-block_configurablereports#98]
The pix_url() function was deprecated as of Moodle 3.3. All instances should be replaced appropriately with pix_icon (in most places) and image_url for the case of setting a background image in CSS.

The 3 files are:

- editcomp.php
- managereport.php
- locallib.php

Best regards,

Michael Milette

**Comment by michael-milette** [comment]
Seems to be addressed by pull request https://github.com/jleyva/moodle-block_configurablereports/pull/96

**Comment by sarjona** [comment]
Michael, thank you for reporting it! :-) 

It has been fixed in https://github.com/jleyva/moodle-block_configurablereports/commit/d2a5578433e8d66d5033bfc6ed01b7294a503528

Most of the calls have been replaced by the **pix_icon** methods. Only the ones referring to the background image in CSS now use the **image_url**.
